FROM zabbix/zabbix-server-pgsql:alpine-latest

USER root

#RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
#    apk add --no-cache curl

RUN apk add --no-cache curl

USER 1997