ARG ES_VERSION=7.13.2

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

ARG ES_VERSION

#USER root

#RUN \
#  /usr/share/elasticsearch/bin/elasticsearch-plugin install -b \
#  https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/"$ES_VERSION".0/prometheus-exporter-"$ES_VERSION".0.zip

#USER elasticsearch

RUN \
  /usr/share/elasticsearch/bin/elasticsearch-plugin install \
  https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${ES_VERSION}/elasticsearch-analysis-ik-${ES_VERSION}.zip && \
  /usr/share/elasticsearch/bin/elasticsearch-plugin install -b \
  https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/"$ES_VERSION".0/prometheus-exporter-"$ES_VERSION".0.zip



#USER elasticsearch