name: Build Elasticsearch Prometheus-exporter Image CI

on:
  push:
    branches: [main]
    paths:
      - './elasticsearch/Dockerfile-prometheus-exporter'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Elasticsearch
        uses: docker/build-push-action@v2
        with:
          file: ./elasticsearch/Dockerfile-prometheus-exporter
          context: ./elasticsearch
          push: true
          tags: peytonyip/elasticsearch:prometheus-exporter
      
