name: Build PHP-7.3-alpine Docker Image CI

on:
  push:
    branches: [main]
    paths:
    - './php/Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PHP
        uses: docker/build-push-action@v2
        with:
          file: ./php/Dockerfile
          context: .
          push: true
          tags: peytonyip/php:7.3-alpine
      
