name: Build Kibana Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - './kibana/Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Kibana
        uses: docker/build-push-action@v6
        with:
          file: ./kibana/Dockerfile
          context: .
          push: true
          tags: peytonyip/kibana
      
