name: Build Grafana Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - './grafana/Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Grafana
        uses: docker/build-push-action@v4
        with:
          file: ./grafana/Dockerfile
          context: .
          build-args: |
            GRAFANA_VERSION=latest
            GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
          push: true
          tags: peytonyip/grafana
      
