name: Build maven Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - './maven/Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push maven
        uses: docker/build-push-action@v6
        with:
          file: ./maven/Dockerfile
          context: .
          push: true
          tags: peytonyip/maven:3-eclipse-temurin-21-alpine
      
