name: Build logstash Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - './logstash/Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push logstash
        uses: docker/build-push-action@v4
        with:
          file: ./logstash/Dockerfile
          context: .
          push: true
          tags: |
            peytonyip/logstash
            peytonyip/logstash:ip2region
    
