name: Build Fluentd Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - './fluentd/Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Fluentd
        uses: docker/build-push-action@v3
        with:
          file: ./fluentd/Dockerfile
          context: .
          push: true
          tags: peytonyip/fluentd
      
