name: Build Nginx Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'nginx/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'nginx/Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Nginx
        uses: docker/build-push-action@v2
        with:
          file: ./nginx/Dockerfile
          context: .
          push: true
          tags: |
            peytonyip/nginx-brotli:stable

