name: Build Jenkins Alpine Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - './jenkins/Dockerfile-alpine'
  schedule:
    - cron: '0 21 * * 4'
  
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Jenkins Alpine
        uses: docker/build-push-action@v2
        with:
          file: ./jenkins/Dockerfile-alpine
          context: ./jenkins
          push: true
          tags: peytonyip/jenkins:alpine
      
